stages:
  - Unit_Test
  - Deploy_Standalone
  - Deploy_AnyPoint
  - Deploy_CloudHub
  
Unit_Test:
  stage: Unit_Test
  script:
    - sh 'mvn clean test'
    
Deploy_Standalone:
  stage: Deploy_Standalone
  script:
    - sh 'mvn deploy -P standalone'
    
Deploy_AnyPoint:
  stage: Deploy_AnyPoint
  variables:
    ANYPOINT_CREDENTIALS: credentials('anypoint.credentials')
  script:
    - "sh 'mvn deploy -P arm -Darm.target.name=local-4.0.0-ee -Danypoint.username=${ANYPOINT_CREDENTIALS_USR}\
      \  -Danypoint.password=${ANYPOINT_CREDENTIALS_PSW}'"
      
Deploy_CloudHub:
  stage: Deploy_CloudHub
  variables:
    ANYPOINT_CREDENTIALS: credentials('anypoint.credentials')
  script:
    - "sh 'mvn deploy -P cloudhub -Dmule.version=4.0.0 -Danypoint.username=${ANYPOINT_CREDENTIALS_USR}\
      \ -Danypoint.password=${ANYPOINT_CREDENTIALS_PSW}'"